### ISSUE TITLE
Instalirane aplikacije - crash

### ISSUE THREAD

**Issue by dakyst** [MASVA/MA-XML-9.0-CROATIAN#1]
Bok Masva,

Instalirao sam novi MIUI 9 Global Beta 7.12.1 na Mi 6 i kada hoću vidjeti u postavkama "Instalirane aplikacije", aplikacija "Postavke" se sruši i vrati me na početni zaslon. To se ne događa kad promijenim jezik telefona na Engleski (US).

Hvala unaprijed na pomoći!

**Comment by MASVA** [comment]
ne znam zašto je tako
ja koristim .eu ROM 7.30.11 i nemam tih problema
probaj druge jezike pa javi
nešto je s prijevodom očito u pitanju

**Comment by dakyst** [comment]
Hvala na brzom odgovoru! Pričekat ću idući petak, možda novi update riješi problem :)

**Comment by MASVA** [comment]
kako je na drugim jezicima?
prijevod za global inače prijavi na en.miui ili preko PM

**Comment by dakyst** [comment]
Evo probao sam na njemačkom, francuskom, talijanskom i još nekim i na svakom se ruši, jedino na English (UK) i (USA) radi ok.
Može, prijavit ću grešku na official forumu.
